publish_to: none

name: dtorrent_task
description: BitTorrent download client package written by pure Dart language.
version: 0.4.0
repository: https://github.com/moham96/dtorrent_task
issue_tracker: https://github.com/moham96/dtorrent_task/issues

environment:
  sdk: "3.8.0"

dependencies:
  dtorrent_parser:
    path: C:/Users/Felipe/Desktop/Projetinhos/packages_clone/dtorrent_parser-1.0.8
  dtorrent_tracker:
    path: C:/Users/Felipe/Desktop/Projetinhos/packages_clone/dtorrent_tracker-1.3.18
  bittorrent_dht:
    path: C:/Users/Felipe/Desktop/Projetinhos/packages_clone/bittorrent_dht-0.0.12
  dtorrent_common:
    path: C:/Users/Felipe/Desktop/Projetinhos/packages_clone/dtorrent_common-1.0.7
  b_encode_decode: ^1.0.4
  utp_protocol: ^1.0.4
  dart_ipify: ^1.1.1
  events_emitter2: ^1.0.3
  mime: ^1.0.4
  collection: ^1.0.0
  crypto: ^3.0.3
  args: ^2.4.2
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.0.1
  path: ^1.8.3
  test: ^1.24.3
